### ISSUE TITLE
GitHub Flavored Markdown Support

### ISSUE THREAD

**Issue by philipnewcomer** [AwsmApps/LightPaper-Support#13]
Thanks for making the best markdown editor for the Mac that I've found so far! The only thing lacking that would make it perfect is support for <a href="https://help.github.com/articles/github-flavored-markdown">GitHub Flavored Markdown</a>. I know there's already an issue open for GitHub Tables (#11), but this is about the full GFM feature set.  I use GFM for marking up all of my text documents, and this is the only thing keeping me from switching to LightPaper for Mac full-time. I'd even be willing to pay for a version that had GFM support if necessary.

**Comment by ashokgelal** [comment]
I've implemented full GFM support in the latest LightPaper version 1.0 (will be out very soon).

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md).

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#30

**Comment by dfalster** [comment]
Nice work, congrats!
