### ISSUE TITLE
Open in new window

### ISSUE THREAD

**Issue by hnishide** [AwsmApps/LightPaper-Support#20]
Dragging a tab out of the window and open a new window for it.

**Comment by ashokgelal** [comment]
This has now been implement in the latest ver 1.0, which will be out very soon.

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md).

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#29
