### ISSUE TITLE
Support for Task syntax

### ISSUE THREAD

**Issue by ndarville** [AwsmApps/LightPaper-Support#23]
As seen [on GitHub](https://github.com/blog/1825-task-lists-in-all-markdown-documents).

**Comment by ashokgelal** [comment]
This has been implemented in the latest 1.0 version which will be out very soon.

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md).

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#28
