### ISSUE TITLE
Feature Request: Table Editor

### ISSUE THREAD

**Issue by getaaron** [AwsmApps/LightPaper-Support#26]
Right now, I use http://www.tablesgenerator.com/markdown_tables and paste it into LightPaper, which is clumsy.

LightPaper should have a simple, built-in table editor.  I'd be happy to work on this if LightPaper is open-source, but I don't see the source anywhere.

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#26
