### ISSUE TITLE
Disable Markdown highlighting in code blocks

### ISSUE THREAD

**Issue by danielr** [AwsmApps/LightPaper-Support#29]
In the editor window, markdown highlighting should probably be disabled for code blocks, otherwise they might look funky:

![screen shot 2014-06-04 at 10 16 17](https://cloud.githubusercontent.com/assets/76049/3171035/b59af1ea-ebc0-11e3-96b5-8aa704d7a371.png)

Especially the highlight of headings is problematic, since `#` is often used in code (comments in many languages, or `#import`).

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#24
