### ISSUE TITLE
Image not Refreshing after change

### ISSUE THREAD

**Issue by peercube** [AwsmApps/LightPaper-Support#30]
1. Embed an image from web using a web link preceded by ! mark.  ![Image from Web](http://www.xyz.com/image.png) in a markdown document.
2. Change the image at the source location. The URL and filename of image still same as before.
3. LightPaper doesn't refresh and show the new image in Preview and Export to PDF and still shows the old image.

I couldn't locate where LightPaper is caching the old image locally. I cleared Cache in Safari but not change in behavior. I am using LightPaper version 0.9 (20) on rMBP with OSX Maverick.

**Comment by jsangrador** [comment]
Hi, FWIW I am seeing the same behavior with local images. Images change but the preview sticks to the old images. Working workarounds: close LightPaper and reopen it; also removing the nag and readding it seems to work around the problem.

Thanks for this useful editor, BTW.

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#23
