### ISSUE TITLE
⇧⌘[ and ⇧⌘] should switch tabs.

### ISSUE THREAD

**Issue by getaaron** [AwsmApps/LightPaper-Support#31]
**⇧⌘[** and **⇧⌘]** should switch tabs like in Safari and Finder.

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#21

**Comment by ashokgelal** [comment]
This has been now fixed and will be in the latest ver 1.0 release which will be out very very soon.

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md).

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#22
