### ISSUE TITLE
Save… in File menu shouldn't have an ellipses when editing an existing file

### ISSUE THREAD

**Issue by getaaron** [AwsmApps/LightPaper-Support#32]
1. Open a file
2. Press the **File** menu

I expect to see: "Save"
I actually see: "Save…"

Since the action doesn't show a prompt, the **…** should be removed, because it falsely indicates that a modal will be presented before taking an action.

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#20
