### ISSUE TITLE
Syntax Highlighting on Code Blocks not working

### ISSUE THREAD

**Issue by susanBuck** [AwsmApps/LightPaper-Support#33]
Is there a trick to get the syntax highlighting on code blocks to work? 

Not seeing it - [screensot](http://note.io/1mlxznL)

Using Version 0.9 

Syntax highlighting is enabled in prefs: [screenshot](http://note.io/1mlxzn)

**Comment by pavelloz** [comment]
Is there any chance you could unify the prismjs API within LightPaper with github markdown api?

It would be a killer feature for me to have a document that I can write in LightPaper and just copy over to the wiki at github.

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#19

**Comment by ashokgelal** [comment]
FYI, this has been resolved in the latest ver 1.0. No need to add `lang-` anymore. 

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md).
