### ISSUE TITLE
Energy usage

### ISSUE THREAD

**Issue by getaaron** [AwsmApps/LightPaper-Support#36]
After leaving LightPaper running for >1 hour

• My MacBook Pro fans spin up
• Activity Monitor's Energy pane shows LightPaper has an "Energy Impact" of over 100
• After quitting LightPaper, the fans turn off

Let me know if there are any log files that might help diagnose this.

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#17
