### ISSUE TITLE
local images not rendering in preview

### ISSUE THREAD

**Issue by grrrwaaa** [AwsmApps/LightPaper-Support#43]
E.g. 

```
![my local image](img/foo.jpg)
```

Shouldn't this be able to look into the img/ folder next to the .md file?

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#11

**Comment by ashokgelal** [comment]
FYI, rendering of local images has been improved in the latest ver 1.0 (will be out soon)

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md). (will be out very soon)
