### ISSUE TITLE
What happened to LightPaper?

### ISSUE THREAD

**Issue by canadaduane** [AwsmApps/LightPaper-Support#45]
As far as I can tell, the app is no longer in the Google Play store, the website is down, and even ClockworkEngine is unresolvable. Such a promising app. So sad to see it go dark. :(

**Comment by robmoggach** [comment]
could not agree more - such a great app - beats ulysses, sublime, and any other of the notetaking/writing/snippet/markdown etc. apps for robust markdown editing - love it and hopefully it doesn't die

**Comment by sytpp** [comment]
After searching and comparing maaaaany md editing apps I also found LightPaper the best by far! Now, I wanted to include an image and there seems to be a bug that was never resolved :( 
![caption](image.jpg) doesn't work for me. Did anyone hear from Lightpaper support?

**Comment by canadaduane** [comment]
I have not.

**Comment by ashokgelal** [comment]
Not dead yet :)

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md). (will be out very soon)

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#9
