### ISSUE TITLE
Objective-C code highlighting?

### ISSUE THREAD

**Issue by mhergon** [AwsmApps/LightPaper-Support#47]
Hi,

Is there support for Objective-C code highlighting?

Thanks!

**Comment by ashokgelal** [comment]
FYI, syntax highlighting has improved in the latest LightPaper version 1.0 (will be out very soon).

Here is a list of new features, improvements, and bug fixes in version 1.0: [Release Notes v1.0](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md).

**Comment by ashokgelal** [comment]
This issue was moved to 42Squares/LightPaper#7

**Comment by mhergon** [comment]
@ashokgelal Thanks!
