### ISSUE TITLE
Is there an option to launch lightpaper and only display the preview window?

### ISSUE THREAD

**Issue by cjus** [AwsmApps/LightPaper-Support#56]
I'd like to do this:

```shell
$ open -a lightpaper README.md -p preview
```

or something like that..

The usecase is working in my code editor (atom/vi) and having only a live preview window open to render my markdown changes.

**Comment by ashokgelal** [comment]
There isn't but if you want, you could open LightPaper's external preview window (CMD+3), minimize LightPaper (not the external preview window) and then edit the file in any other editor. Obviously, you do have to save the changes to see the preview.

I don't do this and is not officially supported so there might be annoyances that you may not like.

**Comment by cjus** [comment]
@ashokgelal thanks for the reply. That's actually what I do!  Was looking for something a bit more automagical. Thanks again. Feel free to close this issue.
