### ISSUE TITLE
Question about RTL Languages

### ISSUE THREAD

**Issue by chieftaha** [AwsmApps/LightPaper-Support#58]
I am wondering if there is a support for rtl languages (Persian, Arabic, Hebrew). I already tried to add a custom editor template, adding a `direction: rtl` on each class (H1, H2, etc, except Code), just like how it works in css, but unsuccessful.  
```
H1
foreground: d4430d
font-size: 18px
direction: rtl 

H2
foreground: d4430d
font-size: 16px
direction: rtl
```
Do I miss something?

**Comment by ashokgelal** [comment]
RTL is not supported officially, unfortunately.
